apiVersion: apps/v1
kind: Deployment
metadata:
  name: binarycalculator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker
  template:
    metadata:
      labels:
        app: docker
    spec:
      containers:
        - image: northamerica-northeast2-docker.pkg.dev/quality-lab-deliverable-3/sofe3980u/binarycalculator
          name: docker
          ports:
            - containerPort: 8080
              name: docker