apiVersion: apps/v1
kind: Deployment
metadata:
  name: binarycalculator-deployment
  labels:
    app: binarycalculator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: binarycalculator
  template:
    metadata:
      labels:
        app: binarycalculator
    spec:
      containers:
      - name: binarycalculator
        image: northamerica-northeast2-docker.pkg.dev/trans-sanctum-415923/sofe3980u/binarycalculator
        ports:
        - containerPort: 8080
